version: "3.1"

services:
  wordpress:
#    image: us-west1-docker.pkg.dev/etc-wordpress-site-staging/website-staging/website:latest
    container_name: wordpress
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp-files:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - db:/var/lib/mysql
      - ./db.sql:/db.sql

volumes:
  db:
  wp-files: