version: "3.1"

services:
  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'https://wordpress.etc-website-image.orb.local');
        define('WP_HOME', 'https://wordpress.etc-website-image.orb.local');
        define('WP_STATELESS_MEDIA_CACHE_BUSTING', 'true');
        define('WP_STATELESS_MEDIA_MODE', 'ephemeral');
        define('WP_STATELESS_MEDIA_BUCKET', 'production-website-assets');
        define('WP_STATELESS_MEDIA_BODY_REWRITE', 'true');
    volumes:
      - ./wp-content/bcf-fonts:/var/www/html/wp-content/bcf-fonts
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - db:/var/lib/mysql
      - ./db.sql:/db.sql

volumes:
  db:
  wp-files:
